### ISSUE TITLE
Todo B

### ISSUE THREAD

**Issue by alexisabril** [alexisabril/sandbox#7]
## Copilot Partner Program: Onboarding

- Zendesk links:
- SFDC Partner Record:

## Signer Info:

- Name:
- Title:
- Email:

```[tasklist]
### Docs:
- [ ] TPP sent
- [ ] TPP signed
- [ ] Copilot Terms sent
- [ ] Copilot Terms signed
- [ ] AUP sent
- [ ] AUP signed
- [ ] Microsoft NDA signed
- [ ] API Doc Sent
- [ ] Changelog post
```

```[tasklist]
### Engineering:
- [ ] task
```

_Original issue: [Todo B](https://api.github.com/repos/alexisabril/sandbox/issues/4)_
